# Generated by Django 6.0.1 on 2026-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='vision/')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5)),
            ],
            options={
                'verbose_name': 'Vision Section',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
