# Generated by Django 6.0.1 on 2026-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corevalue_visionsection_sitesettings_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main CTA heading', max_length=255)),
                ('title_en', models.CharField(help_text='Main CTA heading', max_length=255, null=True)),
                ('title_ar', models.CharField(help_text='Main CTA heading', max_length=255, null=True)),
                ('button_text', models.CharField(help_text='Button label', max_length=50)),
                ('button_text_en', models.CharField(help_text='Button label', max_length=50, null=True)),
                ('button_text_ar', models.CharField(help_text='Button label', max_length=50, null=True)),
                ('button_link', models.CharField(help_text='URL or anchor (e.g. #contact)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
