# Generated by Django 6.0.1 on 2026-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ctasection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctasection',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL or anchor (e.g. #contact)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='button_text',
            field=models.CharField(blank=True, help_text='Button label', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='button_text_ar',
            field=models.CharField(blank=True, help_text='Button label', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Button label', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='title',
            field=models.CharField(blank=True, help_text='Main CTA heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Main CTA heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Main CTA heading', max_length=255, null=True),
        ),
    ]
