# Generated by Django 6.0.1 on 2026-01-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ctasection_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('site_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('site_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('working_days', models.CharField(blank=True, max_length=200, null=True)),
                ('working_days_en', models.CharField(blank=True, max_length=200, null=True)),
                ('working_days_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours_en', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('sunday_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('sunday_hours_en', models.CharField(blank=True, max_length=100, null=True)),
                ('sunday_hours_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('quick_links', models.JSONField(blank=True, null=True)),
                ('solutions', models.JSONField(blank=True, null=True)),
                ('recent_posts', models.JSONField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_en', models.CharField(blank=True, max_length=200, null=True)),
                ('address_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('copyright_text', models.TextField(blank=True, null=True)),
                ('copyright_text_en', models.TextField(blank=True, null=True)),
                ('copyright_text_ar', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
