# Generated by Django 6.0.1 on 2026-01-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_footersection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visionsection',
            options={},
        ),
        migrations.AddField(
            model_name='visionsection',
            name='section_type',
            field=models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision')], default='vision', max_length=20),
        ),
        migrations.AlterField(
            model_name='visionsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
