# Generated by Django 6.0.1 on 2026-01-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, null=True, unique=True)),
                ('slug_ar', models.SlugField(blank=True, null=True, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
