# Generated by Django 6.0.1 on 2026-01-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sections_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sections',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
    ]
