# Generated by Django 6.0.1 on 2026-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sections_order_sections_show_in_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersection',
            name='recent_posts',
        ),
        migrations.AddField(
            model_name='footersection',
            name='working_dec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
