# Generated by Django 6.0.1 on 2026-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_footersection_recent_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='working_dec_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='working_dec_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
