# Generated by Django 6.0.1 on 2026-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_footersection_working_dec_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersection',
            old_name='sunday_hours',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='footersection',
            old_name='sunday_hours_ar',
            new_name='status_ar',
        ),
        migrations.RenameField(
            model_name='footersection',
            old_name='sunday_hours_en',
            new_name='status_en',
        ),
        migrations.AddField(
            model_name='footersection',
            name='working_off',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='working_off_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='working_off_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
