# Generated by Django 6.0.1 on 2026-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_sunday_hours_footersection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='quick_links_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='quick_links_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='solutions_ar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='solutions_en',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
