# Generated by Django 6.0.1 on 2026-02-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_footersection_quick_links_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-twitter', 'Twitter'), ('fab fa-instagram', 'Instagram'), ('fab fa-linkedin-in', 'LinkedIn'), ('fab fa-youtube', 'YouTube'), ('fab fa-snapchat-ghost', 'Snapchat'), ('fab fa-tiktok', 'TikTok'), ('fab fa-whatsapp', 'WhatsApp'), ('fas fa-mobile-alt', 'Application')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
