# Generated by Django 6.0.1 on 2026-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='background_color',
            field=models.CharField(blank=True, help_text='Enter HEX color for background (e.g., #25D366 for WhatsApp)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='color',
            field=models.CharField(blank=True, help_text='Enter HEX color for background (e.g., #25D366 for WhatsApp)', max_length=7, null=True),
        ),
    ]
