# Generated by Django 6.0.1 on 2026-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_socialmedia_background_color_socialmedia_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Shown in the header (e.g. ٧:٣٠ ص – ٩:٣٠ م)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_ar',
            field=models.CharField(blank=True, help_text='Shown in the header (e.g. ٧:٣٠ ص – ٩:٣٠ م)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_en',
            field=models.CharField(blank=True, help_text='Shown in the header (e.g. ٧:٣٠ ص – ٩:٣٠ م)', max_length=200, null=True),
        ),
    ]
