# Generated by Django 6.0.1 on 2026-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_site_settings_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Enter HEX color for the icon itself (e.g., #ffffff for white)', max_length=7, null=True),
        ),
    ]
