# Generated by Django 6.0.1 on 2026-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_socialmedia_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='preloader_logo',
            field=models.ImageField(blank=True, help_text='اختياري — يظهر فقط في شاشة التحميل. ارفع نسخة بلون مناسب للخلفية الداكنة إن لزم. إذا تُرك فارغًا يُستخدم الشعار الرئيسي.', null=True, upload_to='settings/preloader/', verbose_name='شعار شاشة التحميل'),
        ),
    ]
