# Generated by Django 6.0.1 on 2026-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_preloader_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='preloader_logo',
            field=models.ImageField(blank=True, help_text='Optional. Shown only on the loading screen (e.g. a light logo for a dark background). If empty, the main logo is used.', null=True, upload_to='settings/preloader/', verbose_name='Preloader logo'),
        ),
    ]
