# Generated by Django 6.0.1 on 2026-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_footersection_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='quick_links',
            field=models.JSONField(blank=True, help_text='Example: [{"label": "الخدمات", "url": "services_list"}, {"label": "اتصل بنا", "url": "/#simply-contact"}]', null=True),
        ),
    ]
