# Generated by Django 6.0.5 on 2026-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_footersection_quick_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.DeleteModel(
            name='CTASection',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='VisionSection',
        ),
        migrations.AlterField(
            model_name='footersection',
            name='quick_links',
            field=models.JSONField(blank=True, help_text='Example: [{"title": "من نحن", "url": "about"}, {"title": "خدماتنا", "url": "services"}]. Use "title" or "label". url: home section slug (about, services, our-work, vision, mission, contact) or Django name (contact_form) or path (/page/).', null=True),
        ),
    ]
