# Generated by Django 6.0.5 on 2026-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='social_links',
            field=models.JSONField(blank=True, help_text='Example: [{"platform": "instagram", "url": "https://instagram.com/yourpage"}, {"platform": "x", "url": "https://x.com/yourpage"}]. platform: facebook, instagram, x (or twitter), youtube, snapchat, linkedin, whatsapp. Leave empty to use Instagram URL below or Site Settings social fields.', null=True, verbose_name='Social media links'),
        ),
    ]
