# Generated by Django 6.0.5 on 2026-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_footer_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='snapchat_url',
            field=models.URLField(blank=True, null=True, verbose_name='Snapchat profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='snapchat',
            field=models.URLField(blank=True, null=True, verbose_name='Snapchat profile URL'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='social_links',
            field=models.JSONField(blank=True, help_text='Example: [{"platform": "snapchat", "url": "https://www.snapchat.com/add/yourpage"}, {"platform": "instagram", "url": "https://instagram.com/yourpage"}, {"platform": "x", "url": "https://x.com/yourpage"}]. platform: facebook, instagram, x (or twitter), youtube, snapchat, linkedin, whatsapp. Leave empty to use Instagram URL below or Site Settings social fields.', null=True, verbose_name='Social media links'),
        ),
    ]
