# Generated by Django 6.0.1 on 2026-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_tiktok_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_red',
            field=models.CharField(blank=True, default='#E30613', help_text='HEX code for --rs-theme-red (buttons, links, accents). Example: #E30613', max_length=7, null=True, verbose_name='Theme red'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
    ]
