# Generated by Django 6.0.1 on 2026-01-30 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutsection_herosection_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
