# Generated by Django 6.0.1 on 2026-01-30 14:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_aboutsection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_ar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
