# Generated by Django 6.0.1 on 2026-01-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_herosection_title_alter_herosection_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='logo_m_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
