# Generated by Django 6.0.1 on 2026-01-30 21:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_herosection_logo_m_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='who_we_are/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='who_we_are/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='who_we_are/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='who_we_are/')),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAreFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('column', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2')], default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.whowearesection')),
            ],
        ),
    ]
