# Generated by Django 6.0.1 on 2026-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_whowearefeature_name_ar_whowearefeature_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='button_link_contact',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_contact_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text_contact_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
