# Generated by Django 6.0.1 on 2026-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_herosection_button_link_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
