# Generated by Django 6.0.1 on 2026-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_herosection_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Subtitle (small line / h4)')),
                ('tagline_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle (small line / h4)')),
                ('tagline_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle (small line / h4)')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Main heading (h1)')),
                ('heading_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main heading (h1)')),
                ('heading_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Main heading (h1)')),
                ('lead', models.TextField(blank=True, verbose_name='Paragraph text')),
                ('lead_en', models.TextField(blank=True, null=True, verbose_name='Paragraph text')),
                ('lead_ar', models.TextField(blank=True, null=True, verbose_name='Paragraph text')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/slides/')),
                ('foreground_image', models.ImageField(blank=True, null=True, upload_to='hero/slides/', verbose_name='Front image (optional)')),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_text_en', models.CharField(blank=True, max_length=80, null=True)),
                ('button_text_ar', models.CharField(blank=True, max_length=80, null=True)),
                ('button_link', models.CharField(blank=True, help_text='Example: /contact/ or full URL. Leave empty to use contact page.', max_length=255)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
