# Generated by Django 6.0.1 on 2026-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_hero_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_video', models.BooleanField(default=False, help_text='When enabled, shows one looping muted video; image carousel is hidden.', verbose_name='Use video instead of image slider')),
                ('background_video', models.FileField(blank=True, help_text='MP4 or WebM. Plays muted, looped, autoplay.', null=True, upload_to='hero/video/', verbose_name='Background video file')),
                ('external_video_url', models.URLField(blank=True, help_text='Direct link to an MP4/WebM file. If set, overrides the uploaded file.', max_length=500, verbose_name='Video URL (optional)')),
            ],
            options={
                'verbose_name': 'Hero banner',
                'verbose_name_plural': 'Hero banner',
            },
        ),
    ]
