# Generated by Django 6.0.1 on 2026-05-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_hero_banner_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroOverlayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/overlay/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_images', to='pages.herobannersettings')),
            ],
            options={
                'verbose_name': 'Hero bottom image',
                'verbose_name_plural': 'Hero bottom images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
