# Generated by Django 6.0.1 on 2026-05-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_hero_overlay_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlideBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/slides/bg/', verbose_name='Background image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_backgrounds', to='pages.heroslide', verbose_name='Hero slide')),
            ],
            options={
                'verbose_name': 'Hero slide extra background',
                'verbose_name_plural': 'Hero slide extra backgrounds',
                'ordering': ['order', 'id'],
            },
        ),
    ]
