# Generated by Django 6.0.1 on 2026-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_hero_slide_extra_backgrounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_work/', verbose_name='الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر')),
            ],
            options={
                'verbose_name': 'صورة أعمالنا',
                'verbose_name_plural': 'صور أعمالنا',
                'ordering': ['order', 'id'],
            },
        ),
    ]
