# Generated by Django 6.0.1 on 2026-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_our_work_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourworkimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Our work item', 'verbose_name_plural': 'Our work items'},
        ),
        migrations.AddField(
            model_name='ourworkimage',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 or WebM. Use this or image — not both.', null=True, upload_to='our_work/video/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='ourworkimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Use this or video — not both.', null=True, upload_to='our_work/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ourworkimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='ourworkimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display order'),
        ),
    ]
