# Generated by Django 6.0.1 on 2026-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_mission_vision_values_and_final_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvvtabbullet',
            name='text_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='Line text'),
        ),
        migrations.AlterField(
            model_name='mvvtabbullet',
            name='text_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Line text'),
        ),
    ]
