# Generated by Django 6.0.1 on 2026-05-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_shared_mvv_block_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='button_text_ar',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_text_contact_ar',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_text_contact_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_text_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='whowearefeature',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='whowearefeature',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='whowearesection',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='whowearesection',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='whowearesection',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='whowearesection',
            name='title_en',
        ),
    ]
