# Generated by Django 6.0.1 on 2026-05-16 09:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_herosection_button_text_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalwordsection',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional. Prefer «Final word — column lines» below for two side-by-side columns.', null=True, verbose_name='Body (legacy)'),
        ),
        migrations.AlterField(
            model_name='finalwordsection',
            name='body_ar',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional. Prefer «Final word — column lines» below for two side-by-side columns.', null=True, verbose_name='Body (legacy)'),
        ),
        migrations.AlterField(
            model_name='finalwordsection',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional. Prefer «Final word — column lines» below for two side-by-side columns.', null=True, verbose_name='Body (legacy)'),
        ),
        migrations.CreateModel(
            name='FinalWordColumnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Line text')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Line text')),
                ('text_ar', models.CharField(max_length=500, null=True, verbose_name='Line text')),
                ('column', models.PositiveSmallIntegerField(choices=[(1, 'Column 1'), (2, 'Column 2')], default=1, verbose_name='Column')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_lines', to='pages.finalwordsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Final word — column line',
                'verbose_name_plural': 'Final word — column lines',
                'ordering': ['order', 'id'],
            },
        ),
    ]
