# Generated by Django 6.0.1 on 2026-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_final_word_column_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalwordsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Leave empty: two text columns use the full width. Upload a file: image appears beside the text (50/50).', null=True, upload_to='final_word/', verbose_name='Side image (optional)'),
        ),
    ]
