# Generated by Django 6.0.1 on 2026-05-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_finalwordsection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Example: "Our services" / «خدماتنا»', max_length=200, verbose_name='Section title')),
                ('title_en', models.CharField(blank=True, help_text='Example: "Our services" / «خدماتنا»', max_length=200, null=True, verbose_name='Section title')),
                ('title_ar', models.CharField(blank=True, help_text='Example: "Our services" / «خدماتنا»', max_length=200, null=True, verbose_name='Section title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Intro text (under title)')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Intro text (under title)')),
                ('subtitle_ar', models.TextField(blank=True, null=True, verbose_name='Intro text (under title)')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5, verbose_name='Language row')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Home — our services (4 cards)',
                'verbose_name_plural': 'Home — our services (4 cards)',
            },
        ),
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Card title')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Card title')),
                ('title_ar', models.CharField(max_length=120, null=True, verbose_name='Card title')),
                ('text', models.TextField(verbose_name='Card text')),
                ('text_en', models.TextField(null=True, verbose_name='Card text')),
                ('text_ar', models.TextField(null=True, verbose_name='Card text')),
                ('link_url', models.CharField(blank=True, help_text='Optional. Path (#our-work), URL name (services_list), or full URL.', max_length=500, verbose_name='Read more link')),
                ('link_label', models.CharField(blank=True, default='', help_text='Leave empty for default «Read more».', max_length=80, verbose_name='Read more label')),
                ('link_label_en', models.CharField(blank=True, default='', help_text='Leave empty for default «Read more».', max_length=80, null=True, verbose_name='Read more label')),
                ('link_label_ar', models.CharField(blank=True, default='', help_text='Leave empty for default «Read more».', max_length=80, null=True, verbose_name='Read more label')),
                ('icon', models.ImageField(blank=True, help_text='Bottom corner icon. If empty, a default icon is used.', null=True, upload_to='services/icons/', verbose_name='Icon (optional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Orange style by default (like the center card in the theme).', verbose_name='Highlighted card')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pages.homeservicessection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Service card',
                'verbose_name_plural': 'Service cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
