# Generated by Django 6.0.1 on 2026-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_home_services_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeservicecard',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Service item', 'verbose_name_plural': 'Service items'},
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='link_label',
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='link_label_ar',
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='link_label_en',
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='text',
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='text_ar',
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='text_en',
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='intro',
            field=models.TextField(blank=True, help_text='One line before the bullet list, if needed.', verbose_name='Short intro (optional)'),
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='intro_ar',
            field=models.TextField(blank=True, help_text='One line before the bullet list, if needed.', null=True, verbose_name='Short intro (optional)'),
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='intro_en',
            field=models.TextField(blank=True, help_text='One line before the bullet list, if needed.', null=True, verbose_name='Short intro (optional)'),
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='points',
            field=models.TextField(blank=True, help_text='One service point per line (each line becomes a bullet).', verbose_name='Bullet points'),
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='points_ar',
            field=models.TextField(blank=True, help_text='One service point per line (each line becomes a bullet).', null=True, verbose_name='Bullet points'),
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='points_en',
            field=models.TextField(blank=True, help_text='One service point per line (each line becomes a bullet).', null=True, verbose_name='Bullet points'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='footer_note',
            field=models.TextField(blank=True, help_text='Optional paragraph shown under all four service cards (e.g. supervision by engineering team).', verbose_name='Closing note (below cards)'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='footer_note_ar',
            field=models.TextField(blank=True, help_text='Optional paragraph shown under all four service cards (e.g. supervision by engineering team).', null=True, verbose_name='Closing note (below cards)'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='footer_note_en',
            field=models.TextField(blank=True, help_text='Optional paragraph shown under all four service cards (e.g. supervision by engineering team).', null=True, verbose_name='Closing note (below cards)'),
        ),
        migrations.AlterField(
            model_name='homeservicecard',
            name='title',
            field=models.CharField(blank=True, help_text='Example: «Foundation works» / «أعمال الأساسات».', max_length=160, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='homeservicecard',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Example: «Foundation works» / «أعمال الأساسات».', max_length=160, null=True, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='homeservicecard',
            name='title_en',
            field=models.CharField(blank=True, help_text='Example: «Foundation works» / «أعمال الأساسات».', max_length=160, null=True, verbose_name='Service name'),
        ),
    ]
