# Generated by Django 6.0.5 on 2026-05-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_refresh_home_services_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='WhoWeAreFeature',
        ),
        migrations.DeleteModel(
            name='WhoWeAreSection',
        ),
    ]
