# Generated by Django 6.0.1 on 2026-09-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_unused_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Section title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Section title')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Section title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Intro text (under title)')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Intro text (under title)')),
                ('subtitle_ar', models.TextField(blank=True, null=True, verbose_name='Intro text (under title)')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5, verbose_name='Language row')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Home — partners',
                'verbose_name_plural': 'Home — partners',
            },
        ),
        migrations.AlterField(
            model_name='homeofferstrip',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5),
        ),
        migrations.CreateModel(
            name='HomePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Partner name')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Partner name')),
                ('name_ar', models.CharField(max_length=160, null=True, verbose_name='Partner name')),
                ('description', models.TextField(blank=True, verbose_name='Short description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo (optional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='pages.homepartnerssection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
