# Generated by Django 6.0.1 on 2026-09-15 21:02

import django.db.models.deletion
from django.db import migrations, models


def link_slides_to_banner(apps, schema_editor):
    HeroBannerSettings = apps.get_model("pages", "HeroBannerSettings")
    HeroSlide = apps.get_model("pages", "HeroSlide")
    banner, _ = HeroBannerSettings.objects.get_or_create(
        pk=1,
        defaults={"prefer_video": False},
    )
    HeroSlide.objects.filter(banner__isnull=True).update(banner=banner)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_home_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='pages.herobannersettings', verbose_name='Hero banner'),
        ),
        migrations.RunPython(link_slides_to_banner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Main slider image. Recommended size: 1920×950.', null=True, upload_to='hero/slides/', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_link',
            field=models.CharField(blank=True, help_text='Example: /#homecontact or a full URL. Leave empty to scroll to contact.', max_length=255, verbose_name='Button link'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text_ar',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Button text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Main heading'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='heading_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main heading'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='heading_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main heading'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle (small line)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='tagline_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle (small line)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle (small line)'),
        ),
    ]
