# Generated by Django 6.0.1 on 2026-09-15 21:59

import django.db.models.deletion
from django.db import migrations, models

LEGACY_COLUMNS = ("column_1", "column_2", "column_3")
TRANSLATED_SUFFIXES = ("", "_en", "_ar")


def columns_to_items(apps, schema_editor):
    Strip = apps.get_model("pages", "HomeOfferStrip")
    Item = apps.get_model("pages", "HomeOfferItem")
    for strip in Strip.objects.all():
        for order, prefix in enumerate(LEGACY_COLUMNS, start=1):
            if not (
                getattr(strip, f"{prefix}_title") or getattr(strip, f"{prefix}_text")
            ):
                continue
            values = {}
            for field in ("title", "text"):
                for suffix in TRANSLATED_SUFFIXES:
                    legacy = getattr(strip, f"{prefix}_{field}{suffix}")
                    values[f"{field}{suffix}"] = (
                        legacy if suffix else (legacy or "")
                    )
            Item.objects.create(strip=strip, order=order, **values)


def items_to_columns(apps, schema_editor):
    Item = apps.get_model("pages", "HomeOfferItem")
    for strip_id in Item.objects.values_list("strip_id", flat=True).distinct():
        items = list(
            Item.objects.filter(strip_id=strip_id).order_by("order", "id")[
                : len(LEGACY_COLUMNS)
            ]
        )
        strip = items[0].strip
        for prefix, item in zip(LEGACY_COLUMNS, items):
            for field in ("title", "text"):
                for suffix in TRANSLATED_SUFFIXES:
                    setattr(
                        strip,
                        f"{prefix}_{field}{suffix}",
                        getattr(item, f"{field}{suffix}"),
                    )
        strip.save()
    Item.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_heroslide_banner_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeofferstrip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='homeofferstrip',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5, verbose_name='Language row'),
        ),
        migrations.CreateModel(
            name='HomeOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Example: "+12 Years of Experience".', max_length=120, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, help_text='Example: "+12 Years of Experience".', max_length=120, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, help_text='Example: "+12 Years of Experience".', max_length=120, null=True, verbose_name='Title')),
                ('text', models.TextField(blank=True, help_text='Leave empty to show the icon and title only.', verbose_name='Text (optional)')),
                ('text_en', models.TextField(blank=True, help_text='Leave empty to show the icon and title only.', null=True, verbose_name='Text (optional)')),
                ('text_ar', models.TextField(blank=True, help_text='Leave empty to show the icon and title only.', null=True, verbose_name='Text (optional)')),
                ('icon', models.ImageField(blank=True, help_text='Around 70×70 px. If empty, a default theme icon is used.', null=True, upload_to='offer_strip/icons/', verbose_name='Icon (optional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('strip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.homeofferstrip', verbose_name='Strip')),
            ],
            options={
                'verbose_name': 'Offer strip item',
                'verbose_name_plural': 'Offer strip items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(columns_to_items, items_to_columns),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_1_text',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_1_text_ar',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_1_text_en',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_1_title',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_1_title_ar',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_1_title_en',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_2_text',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_2_text_ar',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_2_text_en',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_2_title',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_2_title_ar',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_2_title_en',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_3_text',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_3_text_ar',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_3_text_en',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_3_title',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_3_title_ar',
        ),
        migrations.RemoveField(
            model_name='homeofferstrip',
            name='column_3_title_en',
        ),
    ]
