# Generated by Django 6.0.1 on 2026-09-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_home_offer_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeofferitem',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Paste the icon class from fontawesome.com, e.g. "fa-regular fa-clock" or just "fa-clock". Remix icons ("ri-truck-line") also work.', max_length=120, verbose_name='Icon code (Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='homeofferitem',
            name='icon',
            field=models.ImageField(blank=True, help_text='Used only when no icon code is set. Around 70×70 px. If both are empty, a default theme icon is used.', null=True, upload_to='offer_strip/icons/', verbose_name='Icon image (optional)'),
        ),
    ]
