# Generated by Django 6.0.1 on 2026-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_offer_item_icon_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionvisionvaluesblock',
            options={'verbose_name': 'Home — about / vision / mission / values', 'verbose_name_plural': 'Home — about / vision / mission / values'},
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mvv/about/', verbose_name='Signatory photo (optional)'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='author_signature',
            field=models.ImageField(blank=True, null=True, upload_to='mvv/about/', verbose_name='Signature image (optional)'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='counter_number',
            field=models.PositiveIntegerField(blank=True, help_text='Counts up from zero when scrolled into view. Empty hides the counter box.', null=True, verbose_name='Counter number'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='counter_suffix',
            field=models.CharField(blank=True, default='+', help_text='Printed right after the number, e.g. "+".', max_length=10, verbose_name='Counter suffix'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='counter_title',
            field=models.CharField(blank=True, help_text='Example: "Years of Experience".', max_length=120, verbose_name='Counter label'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='counter_title_ar',
            field=models.CharField(blank=True, help_text='Example: "Years of Experience".', max_length=120, null=True, verbose_name='Counter label'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='counter_title_en',
            field=models.CharField(blank=True, help_text='Example: "Years of Experience".', max_length=120, null=True, verbose_name='Counter label'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='image_large',
            field=models.ImageField(blank=True, help_text='Around 446×512 px. This one has the slide-in reveal animation.', null=True, upload_to='mvv/about/', verbose_name='Large right image'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='image_main',
            field=models.ImageField(blank=True, help_text='Smaller image, around 359×400 px.', null=True, upload_to='mvv/about/', verbose_name='Top-left image'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='intro',
            field=models.TextField(blank=True, help_text='Shown under the title. If empty, the footer About text is used.', verbose_name='Intro paragraph'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='intro_ar',
            field=models.TextField(blank=True, help_text='Shown under the title. If empty, the footer About text is used.', null=True, verbose_name='Intro paragraph'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='intro_en',
            field=models.TextField(blank=True, help_text='Shown under the title. If empty, the footer About text is used.', null=True, verbose_name='Intro paragraph'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Example: "About Us" / «من نحن».', max_length=120, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='subtitle_ar',
            field=models.CharField(blank=True, help_text='Example: "About Us" / «من نحن».', max_length=120, null=True, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Example: "About Us" / «من نحن».', max_length=120, null=True, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='title',
            field=models.CharField(blank=True, help_text='If empty, the site name is used.', max_length=200, verbose_name='Section title'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='title_ar',
            field=models.CharField(blank=True, help_text='If empty, the site name is used.', max_length=200, null=True, verbose_name='Section title'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='title_en',
            field=models.CharField(blank=True, help_text='If empty, the site name is used.', max_length=200, null=True, verbose_name='Section title'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='video_file',
            field=models.FileField(blank=True, help_text='Used only when no video link is set.', null=True, upload_to='mvv/about/video/', verbose_name='Video file'),
        ),
        migrations.AddField(
            model_name='missionvisionvaluesblock',
            name='video_url',
            field=models.URLField(blank=True, help_text='Opens in a popup from the rotating “Watch Video” button. Leave both video fields empty to hide the button.', verbose_name='Video link (YouTube / Vimeo)'),
        ),
    ]
