# Generated by Django 6.0.1 on 2026-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_about_block_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeservicessection',
            options={'verbose_name': 'Home — our services', 'verbose_name_plural': 'Home — our services'},
        ),
        migrations.RenameField(
            model_name='homeservicecard',
            old_name='icon',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='homeservicecard',
            name='image',
            field=models.ImageField(blank=True, help_text='Slides in on the right when the visitor hovers this service (around 636×400 px). A theme image is used when empty.', null=True, upload_to='services/', verbose_name='Service image'),
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='link_url',
            field=models.CharField(blank=True, help_text='Where the title and arrow point. Empty means the contact section.', max_length=300, verbose_name='Link (optional)'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='label',
            field=models.CharField(blank=True, help_text='Example: "Our Awesome Services" / «خدماتنا».', max_length=120, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='label_ar',
            field=models.CharField(blank=True, help_text='Example: "Our Awesome Services" / «خدماتنا».', max_length=120, null=True, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='label_en',
            field=models.CharField(blank=True, help_text='Example: "Our Awesome Services" / «خدماتنا».', max_length=120, null=True, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='homeservicessection',
            name='side_image',
            field=models.ImageField(blank=True, help_text='Fills the right half of the dark section (around 799×928 px). Hidden by the theme on screens narrower than 1366px.', null=True, upload_to='services/', verbose_name='Large side image'),
        ),
    ]
