# Generated by Django 6.0.1 on 2026-09-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_services_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservicecard',
            name='image',
        ),
    ]
