# Generated by Django 6.0.1 on 2026-09-16 10:30

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_drop_service_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHighlightsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Example: "Why Madayin" / «لماذا نحن».', max_length=120, verbose_name='Small label above the title')),
                ('label_en', models.CharField(blank=True, help_text='Example: "Why Madayin" / «لماذا نحن».', max_length=120, null=True, verbose_name='Small label above the title')),
                ('label_ar', models.CharField(blank=True, help_text='Example: "Why Madayin" / «لماذا نحن».', max_length=120, null=True, verbose_name='Small label above the title')),
                ('title', models.CharField(blank=True, help_text='Leave empty to show the cards without a heading.', max_length=200, verbose_name='Section title')),
                ('title_en', models.CharField(blank=True, help_text='Leave empty to show the cards without a heading.', max_length=200, null=True, verbose_name='Section title')),
                ('title_ar', models.CharField(blank=True, help_text='Leave empty to show the cards without a heading.', max_length=200, null=True, verbose_name='Section title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Intro text (under title)')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Intro text (under title)')),
                ('subtitle_ar', models.TextField(blank=True, null=True, verbose_name='Intro text (under title)')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=5, verbose_name='Language row')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Home — highlight cards (numbers)',
                'verbose_name_plural': 'Home — highlight cards (numbers)',
            },
        ),
        migrations.CreateModel(
            name='HomeHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, help_text='Paste the icon class from fontawesome.com, e.g. "fa-regular fa-clock" or just "fa-clock". Remix icons ("ri-truck-line") also work.', max_length=120, verbose_name='Icon code (Font Awesome)')),
                ('number', models.CharField(blank=True, help_text='Example: "+12" or "25". Empty shows the card position instead.', max_length=20, verbose_name='Number')),
                ('title', models.CharField(blank=True, help_text='Example: "Years of Experience".', max_length=120, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, help_text='Example: "Years of Experience".', max_length=120, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, help_text='Example: "Years of Experience".', max_length=120, null=True, verbose_name='Title')),
                ('text', models.TextField(blank=True, help_text='Small line under the title. Leave empty to show the title only.', verbose_name='Text (optional)')),
                ('text_en', models.TextField(blank=True, help_text='Small line under the title. Leave empty to show the title only.', null=True, verbose_name='Text (optional)')),
                ('text_ar', models.TextField(blank=True, help_text='Small line under the title. Leave empty to show the title only.', null=True, verbose_name='Text (optional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.homehighlightssection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Highlight card',
                'verbose_name_plural': 'Highlight cards',
                'ordering': ['order', 'id'],
            },
            bases=(pages.models.IconClassMixin, models.Model),
        ),
    ]
