# Generated by Django 6.0.1 on 2026-09-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_highlight_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homehighlightssection',
            options={'verbose_name': 'Home — stats cards (under services)', 'verbose_name_plural': 'Home — stats cards (under services)'},
        ),
    ]
