# Generated by Django 6.0.1 on 2026-09-16 11:01

import ckeditor.fields
from django.db import migrations, models


def lines_to_paragraphs(apps, schema_editor):
    Section = apps.get_model("pages", "FinalWordSection")
    Line = apps.get_model("pages", "FinalWordColumnLine")
    for section in Section.objects.all():
        if section.paragraph_1 or section.paragraph_2 or section.paragraph_3:
            continue
        texts = [
            (text or "").strip()
            for text in Line.objects.filter(section=section)
            .order_by("column", "order", "id")
            .values_list("text", flat=True)
            if (text or "").strip()
        ]
        if not texts:
            continue
        buckets = ["", "", ""]
        if len(texts) <= 3:
            for index, text in enumerate(texts):
                buckets[index] = text
        else:
            buckets[0] = "\n".join(texts[:-2])
            buckets[1] = texts[-2]
            buckets[2] = texts[-1]
        section.paragraph_1 = buckets[0]
        section.paragraph_1_en = buckets[0]
        section.paragraph_2 = buckets[1]
        section.paragraph_2_en = buckets[1]
        section.paragraph_3 = buckets[2]
        section.paragraph_3_en = buckets[2]
        if not section.label:
            section.label = "Final word"
            section.label_en = "Final word"
        section.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_stats_cards_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwordsection',
            name='label',
            field=models.CharField(blank=True, help_text='Example: "Final word" / «كلمة أخيرة».', max_length=120, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='label_ar',
            field=models.CharField(blank=True, help_text='Example: "Final word" / «كلمة أخيرة».', max_length=120, null=True, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='label_en',
            field=models.CharField(blank=True, help_text='Example: "Final word" / «كلمة أخيرة».', max_length=120, null=True, verbose_name='Small label above the title'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_1',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', verbose_name='Paragraph 1'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_1_ar',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', null=True, verbose_name='Paragraph 1'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_1_en',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', null=True, verbose_name='Paragraph 1'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_2',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', verbose_name='Paragraph 2'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_2_ar',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', null=True, verbose_name='Paragraph 2'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_2_en',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', null=True, verbose_name='Paragraph 2'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_3',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', verbose_name='Paragraph 3'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_3_ar',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', null=True, verbose_name='Paragraph 3'),
        ),
        migrations.AddField(
            model_name='finalwordsection',
            name='paragraph_3_en',
            field=models.TextField(blank=True, help_text='Several lines are fine. Each line break is kept on the page.', null=True, verbose_name='Paragraph 3'),
        ),
        migrations.RunPython(lines_to_paragraphs, noop),
        migrations.AlterField(
            model_name='finalwordsection',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Used only when the three paragraphs below are empty.', null=True, verbose_name='Body (legacy)'),
        ),
        migrations.AlterField(
            model_name='finalwordsection',
            name='body_ar',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Used only when the three paragraphs below are empty.', null=True, verbose_name='Body (legacy)'),
        ),
        migrations.AlterField(
            model_name='finalwordsection',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Used only when the three paragraphs below are empty.', null=True, verbose_name='Body (legacy)'),
        ),
        migrations.AlterField(
            model_name='finalwordsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Fills the dark panel behind the text. The theme overlay (dark on the left, fading out to the right) stays on top of the photo.', null=True, upload_to='final_word/', verbose_name='Background image'),
        ),
    ]
