# Generated by Django 6.0.1 on 2026-09-16 14:12

from pathlib import Path

import django.db.models.deletion
from django.core.files import File
from django.db import migrations, models


def seed_base_partners(apps, schema_editor):
    Section = apps.get_model("pages", "HomeBasePartnersSection")
    Logo = apps.get_model("pages", "HomeBasePartner")
    if Section.objects.exists():
        return
    section = Section.objects.create(language="en", is_active=True)
    thumbs_dir = Path(__file__).resolve().parents[2] / "static" / "assets" / "images" / "brand"
    thumbs = [
        "brand-thumb-09.png",
        "brand-thumb-10.png",
        "brand-thumb-11.png",
        "brand-thumb-12.png",
        "brand-thumb-13.png",
        "brand-thumb-14.png",
    ]
    for order, name in enumerate(thumbs, start=1):
        path = thumbs_dir / name
        if not path.exists():
            continue
        logo = Logo(section=section, order=order, is_active=True)
        with path.open("rb") as fh:
            logo.image.save(name, File(fh), save=True)


def unseed_base_partners(apps, schema_editor):
    Section = apps.get_model("pages", "HomeBasePartnersSection")
    Section.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_truck_dealer_title_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBasePartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Example: "Base Partners" / «الشركاء الأساسيون».', max_length=120, verbose_name='Small label above the title')),
                ('label_en', models.CharField(blank=True, help_text='Example: "Base Partners" / «الشركاء الأساسيون».', max_length=120, null=True, verbose_name='Small label above the title')),
                ('label_ar', models.CharField(blank=True, help_text='Example: "Base Partners" / «الشركاء الأساسيون».', max_length=120, null=True, verbose_name='Small label above the title')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Section title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Section title')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Section title')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5, verbose_name='Language row')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Home — base partners',
                'verbose_name_plural': 'Home — base partners',
            },
        ),
        migrations.CreateModel(
            name='HomeBasePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional. Used as the image alt text.', max_length=160, verbose_name='Name')),
                ('title_en', models.CharField(blank=True, help_text='Optional. Used as the image alt text.', max_length=160, null=True, verbose_name='Name')),
                ('title_ar', models.CharField(blank=True, help_text='Optional. Used as the image alt text.', max_length=160, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, help_text='Add as many logos as you need. They show in a 6-up slider.', null=True, upload_to='base_partners/', verbose_name='Logo')),
                ('link_url', models.URLField(blank=True, verbose_name='Link (optional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='pages.homebasepartnerssection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Base partner logo',
                'verbose_name_plural': 'Base partner logos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_base_partners, unseed_base_partners),
    ]
