# Generated by Django 6.0.1 on 2026-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_base_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebasepartnerssection',
            name='label',
            field=models.CharField(blank=True, help_text='Optional small tag above the title. Leave empty to hide it.', max_length=120, verbose_name='Small tag (optional)'),
        ),
        migrations.AlterField(
            model_name='homebasepartnerssection',
            name='label_ar',
            field=models.CharField(blank=True, help_text='Optional small tag above the title. Leave empty to hide it.', max_length=120, null=True, verbose_name='Small tag (optional)'),
        ),
        migrations.AlterField(
            model_name='homebasepartnerssection',
            name='label_en',
            field=models.CharField(blank=True, help_text='Optional small tag above the title. Leave empty to hide it.', max_length=120, null=True, verbose_name='Small tag (optional)'),
        ),
    ]
