"""
Django settings for core_cms project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mt9cnee45nd^cvnc(&s3os7-=!dq2ac_ya+^*lw17gkkd#3&qa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'jazzmin', # [ENAS CUSTOM] 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    
    # [ENAS CUSTOM]
    'modeltranslation',
    'contact',
    'pages.apps.PagesConfig',
    'core.apps.CoreConfig',
    
    # extra apps
    'ckeditor',             # دا لعرض CKEditor
    'ckeditor_uploader',    # لو هترفعي صور
]

# CKEditor Config
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Basic',
        'height': 280,
        'width': '100%',
        'removePlugins': 'uploadimage,uploadwidget',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',
    'core.middleware.ForceArabicLanguageMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'core_cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # [ENAS CUSTOM]
                'django.template.context_processors.i18n',
                'core.context_processors.site_settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite على أقراص خارجية/بطيئة قد يعلق؛ زيادة المهلة تقلّل أخطاء "database is locked"
        'OPTIONS': {
            'timeout': 30,
        },
    }
}
# أداء التطوير: المشروع على قرص خارجي قد يُبطئ runserver (مراقبة الملفات + SQLite).
# لتجربة أسرع بدون إعادة تحميل تلقائية: python manage.py runserver --noreload


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# The public site is English-only (admin may still use modeltranslation tabs).
LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'



STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# English-only public site (admin may still use modeltranslation tabs).
LANGUAGES = [
    ('en', 'English'),
]

FORCE_SITE_LANGUAGE = 'en'

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

FIXTURE_DIRS = [
    BASE_DIR / 'fixtures',
]

# Modeltranslation settings
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_LANGUAGES = ('en', 'ar')
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'en'


# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL: str = 'accounts.CustomUser'

# LOGOUT_REDIRECT_URL = '/'
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = "/"


JAZZMIN_SETTINGS = {
    "site_title": "CMS Admin",
    "site_header": "CMS Admin",
    "welcome_sign": "Welcome to the CMS",
    "show_sidebar": True,
    "show_navbar": True,
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
}




CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

DEFAULT_FROM_EMAIL = "noreply@madayin.local"
CONTACT_RECIPIENT_EMAIL = ""

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"